on: 
  workflow_dispatch:
    inputs:
      env:
        description: 'env'
        required: true
      subsystem:
        description: 'subsystem'
        required: true
jobs:
  drift_job:
    runs-on: ubuntu-latest
    name: Drift test job
    env:     
      SUB_SYSTEM: asa

    steps:
      - name: Configure AWS Credentials (shared)
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1
          role-skip-session-tagging: true
          role-duration-seconds: 900
          mask-aws-account-id: false
        
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Test s3 script run
        run: |
          export SERVICE_NAME=app-signals-service
          export SERVICE_VERSION=0.16.2
          aws s3 cp s3://artifactory-us-east-1-574574226067/github-workflows/ecr-push.sh .
          chmod u+x ./ecr-push.sh
          ./ecr-push.sh

      # - name: drift action step
      #   id: drift
      #   uses: michaelbammeke/cf-stack-drift@v7
      #   with:
      #     env: ${{ github.event.inputs.env }}
      #     subsystem: ${{ github.event.inputs.subsystem }}
      #     aws-region: "us-east-1"
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-session: ${{ secrets.AWS_SESSION_TOKEN }}